lsi: false
safe: true
incremental: false
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-them
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Board Bits
description: technical bits for the boardroom and engine room
google_analytics: G-49RNLDFGTW
